name: Check for update and send if available

on: 
  schedule: 
    - cron:  '30 8 * * *'

jobs: 
  run:
    runs-on: ubuntu-latest
    container: python:3.11-slim-bullseye
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install pipenv
        python -m venv venv
        source venv/bin/activate
        pipenv install --deploy
    - name: Run script
      run: |
        source venv/bin/activate
        python update.py
      env:
         SENDER_USERNAME: ${{ secrets.SENDER_USERNAME }}
         SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
         RECIPIENTS: ${{ secrets.RECIPIENTS }}
         SEND_MAILS: 1
